[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
cmds = [
    'pip install poetry==1.8.3',
    'poetry config virtualenvs.create false',
    'poetry install --only main'
]

[phases.build]
cmds = ['echo "Build complete"']

[start]
cmd = 'poetry run python -m athena.dashboard.app'