[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/Dockerfile.dashboard"

[deploy]
startCommand = "poetry run python -m athena.dashboard.app"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
PORT = 8050
ATHENA_LOG_LEVEL = "INFO"